import Image from "next/image";
import React from "react";
import img1 from "../../public/assates/about.jpg";

import { useState } from "react";
import Head from "next/head";
import MakeContact from "@/components/makeContact/MakeContact";
import AboutOurUniversity from "@/components/aboutOurUniversity/AboutOurUniversity";
import ScholarshipPrograms from "@/components/scholarshipPrograms/ScholarshipPrograms";
import CampusTour from "@/components/CampusTour/CampusTour";

import CompanyLogo from "@/components/companyLogo/CompanyLogo";






const about = () => {
  const [box1, setBox1] = useState(false);
  const [box2, setBox2] = useState(false);
  const [box3, setBox3] = useState(false);
  const [box4, setBox4] = useState(false);
  return (
    <div>
      {/* Banner */}
      <div className=" relative  saturate-50 ">
        <Image src={img1} alt=" " className="w-full"></Image>
      </div>
      <div className="  absolute left-[12%] lg:left-[50%] top-[50%]    ">
        <h2 className="text-6xl font-bold text-white "> About Us</h2>
      </div>

      {/* A Few Words About the University */}

    <AboutOurUniversity/>
      {/* Scholarship Programs */}
      <ScholarshipPrograms/>
      <div className="mt-20 max-w-[1400px]  m-auto ">
       <div>

       <div>
          <Head>
            <title>about us</title>
            <meta name="description" content="Generated by create next app" />
            
          </Head>
          <div>
           
            <div className=" ">
              <div className="md:py-0 py-5">
                <h1
                  role="heading"
                  className="xl:text-5xl md:text-5xl text-xl font-bold  text-black px-10 pb-8 text-center"
                >
                  Get every single answer here.
                </h1>
                <p className="text-1xl font-semibold text-center px-10   pb-8">
                  A business or organization established to provide a particular
                  service, typically one that involves a organizing
                  transactions.
                </p>
              </div>
              <div className="lg:w-full md:w-8/12 sm:w-9/12 w-full mx-0 lg:mx-10">
                <div className="bg-white shadow rounded p-6  ">
                  <div className="flex items-center justify-between  ">
                    <div>
                      <h2 className="text-base font-semibold leading-none text-gray-800">
                        Why should I do this Courses   ?

                      </h2>
                    </div>
                    <button
                      onClick={() => setBox1(!box1)}
                      className="focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2 ring-offset-white cursor-pointer"
                    >
                       
                      {box1 ? (
                        <svg
                          role="button"
                          aria-label="close dropdown"
                          width="10"
                          height="6"
                          viewBox="0 0 10 6"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M1 5L5 1L9 5"
                            stroke="#4B5563"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      ) : (
                        <svg
                          width="10"
                          role="button"
                          aria-label="open dropdown"
                          height="6"
                          viewBox="0 0 10 6"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M1 1L5 5L9 1"
                            stroke="#4B5563"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      )}
                    </button>
                  </div>

                  {box1 && (
                    <ul className="">
                      <li>
                        <p className="text-base leading-normal text-gray-600 mt-4 lg:w-96">
                          If you want to choose Pro or Business plan the you can
                          use all payments. You can pay from Paypal, Payoneer,
                          Master Card, Debit Card.
                        </p>
                      </li>
                    </ul>
                  )}
                </div>
                <div className="bg-white shadow rounded p-8 mt-8">
                  <div className="flex items-center justify-between">
                    <div>
                      <h2 className="text-base font-semibold leading-none text-gray-800">
                        What payment method I can use?
                      </h2>
                    </div>
                    <button
                      onClick={() => {
                        setBox2(!box2);
                      }}
                      data-menu
                      className="focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2 ring-offset-white cursor-pointer"
                    >
                      {box2 ? (
                        <svg
                          role="button"
                          aria-label="close dropdown"
                          width="10"
                          height="6"
                          viewBox="0 0 10 6"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M1 5L5 1L9 5"
                            stroke="#4B5563"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      ) : (
                        <svg
                          width="10"
                          role="button"
                          aria-label="open dropdown"
                          height="6"
                          viewBox="0 0 10 6"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M1 1L5 5L9 1"
                            stroke="#4B5563"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      )}
                    </button>
                  </div>
                  {box2 && (
                    <ul>
                      <li>
                        <p className="text-base leading-normal text-gray-600 mt-4 lg:w-96">
                          If you want to choose Pro or Business plan the you can
                          use all payments. You can pay from Paypal, Payoneer,
                          Master Card, Debit Card.
                        </p>
                      </li>
                    </ul>
                  )}
                </div>
                <div className="bg-white shadow rounded p-8 mt-8">
                  <div className="flex items-center justify-between">
                    <div>
                      <h2 className="text-base font-semibold leading-none text-gray-800">
                        Is This Courses for  you ?
                      </h2>
                    </div>
                    <button
                      onClick={() => {
                        setBox3(!box3);
                      }}
                      data-menu
                      className="focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2 ring-offset-white cursor-pointer"
                    >
                      {box3 ? (
                        <svg
                          role="button"
                          aria-label="close dropdown"
                          width="10"
                          height="6"
                          viewBox="0 0 10 6"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M1 5L5 1L9 5"
                            stroke="#4B5563"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      ) : (
                        <svg
                          width="10"
                          role="button"
                          aria-label="open dropdown"
                          height="6"
                          viewBox="0 0 10 6"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M1 1L5 5L9 1"
                            stroke="#4B5563"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      )}
                    </button>
                  </div>
                  {box3 && (
                    <ul>
                      <li>
                        <p className="text-base leading-normal text-gray-600 mt-4 lg:w-96">
                          If you want to choose Pro or Business plan the you can
                          use all payments. You can pay from Paypal, Payoneer,
                          Master Card, Debit Card.
                        </p>
                      </li>
                    </ul>
                  )}
                </div>
                <div className="bg-white shadow rounded p-8 mt-8">
                  <div className="flex items-center justify-between">
                    <div>
                      <h2 className="text-base font-semibold leading-none text-gray-800">
                        How to recover password?
                      </h2>
                    </div>
                    <button
                      onClick={() => setBox4(!box4)}
                      data-menu
                      className="focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2 ring-offset-white cursor-pointer"
                    >
                      {box4 ? (
                        <svg
                          role="button"
                          aria-label="close dropdown"
                          width="10"
                          height="6"
                          viewBox="0 0 10 6"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M1 5L5 1L9 5"
                            stroke="#4B5563"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      ) : (
                        <svg
                          width="10"
                          role="button"
                          aria-label="open dropdown"
                          height="6"
                          viewBox="0 0 10 6"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M1 1L5 5L9 1"
                            stroke="#4B5563"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      )}
                    </button>
                  </div>
                  {box4 && (
                    <ul>
                      <li>
                        <p className="text-base leading-normal text-gray-600 mt-4 lg:w-96">
                          If you want to choose Pro or Business plan the you can
                          use all payments. You can pay from Paypal, Payoneer,
                          Master Card, Debit Card.
                        </p>
                      </li>
                    </ul>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
       </div>
       
      </div>
      <CampusTour/>
    
     <CompanyLogo/>
    </div>
  );
};

export default about;
